import { ServiceProvider, Medicine, DiagnosticTest, Booking, Offer, Pharmacy } from './types';
import { PLACEHOLDER_IMAGES } from './placeholder-images';

export const DOCTORS: ServiceProvider[] = [
   {
      id: 'd1',
      name: 'Dr. Anjali Sharma',
      specialization: 'Cardiologist',
      image: PLACEHOLDER_IMAGES.doctors[0],
      rating: 4.8,
      experience: 12,
      clinicAddress: 'Health Plus Clinic, Indiranagar',
      consultationFee: 800,
      availableSlots: ['10:00 AM', '10:30 AM', '04:00 PM', '04:30 PM'],
      homeVisitAvailable: true,
      type: 'doctor',
      about: 'Dr. Anjali Sharma is a renowned Cardiologist with over 12 years of experience. She specializes in interventional cardiology and heart failure management.',
   },
   {
      id: 'd2',
      name: 'Dr. Rajesh Gupta',
      specialization: 'Dermatologist',
      image: PLACEHOLDER_IMAGES.doctors[1],
      rating: 4.5,
      experience: 8,
      clinicAddress: 'Skin Care Center, Koramangala',
      consultationFee: 600,
      availableSlots: ['11:00 AM', '11:45 AM', '05:00 PM', '06:00 PM'],
      homeVisitAvailable: false,
      type: 'doctor',
      about: 'Dr. Rajesh Gupta is a specialist in clinical and cosmetic dermatology. He provides treatments for acne, scars, and anti-aging.',
   },
   {
      id: 'd3',
      name: 'Dr. Emily Lee',
      specialization: 'Pediatrician',
      image: PLACEHOLDER_IMAGES.doctors[2],
      rating: 4.9,
      experience: 15,
      clinicAddress: 'Happy Kids Clinic, Whitefield',
      consultationFee: 700,
      availableSlots: ['09:00 AM', '09:30 AM', '10:00 AM'],
      homeVisitAvailable: true,
      type: 'doctor',
      about: 'Dr. Emily Lee loves working with children and ensures their well-being. She is an expert in child nutrition and vaccination.',
   },
   {
      id: 'd4',
      name: 'Dr. Vikram Patel',
      specialization: 'General Physician',
      image: PLACEHOLDER_IMAGES.doctors[3],
      rating: 4.3,
      experience: 20,
      clinicAddress: 'Community Health Center, Jayanagar',
      consultationFee: 400,
      availableSlots: ['08:00 AM', '08:30 AM', '06:00 PM', '07:30 PM'],
      homeVisitAvailable: true,
      type: 'doctor',
      about: 'Dr. Vikram Patel is a trusted family physician with two decades of experience in treating common ailments and chronic conditions.',
   },
];

export const MEDICINES: Medicine[] = [
   {
      id: 'm1',
      name: 'Paracetamol 500mg',
      manufacturer: 'HealthCorp',
      saltComposition: 'Paracetamol',
      price: 30,
      originalPrice: 40,
      image: PLACEHOLDER_IMAGES.medicines[0],
      prescriptionRequired: false,
      description: 'Effective for fever and mild to moderate pain.',
      benefits: ['Reduces Fever', 'Relieves Pain'],
      sideEffects: ['Nausea', 'Allergic reactions (rare)'],
      directions: 'Take one tablet after food as needed.',
   },
   {
      id: 'm2',
      name: 'Vitamin C 500mg',
      manufacturer: 'VitaLife',
      saltComposition: 'Ascorbic Acid',
      price: 150,
      originalPrice: 200,
      image: PLACEHOLDER_IMAGES.medicines[1],
      prescriptionRequired: false,
      description: 'Boosts immunity and skin health.',
      benefits: ['Immunity Booster', 'Antioxidant', 'Skin Health'],
      sideEffects: ['Stomach upset if taken empty stomach'],
      directions: 'One tablet daily.',
   },
   {
      id: 'm3',
      name: 'Cough Syrup',
      manufacturer: 'CureWell',
      saltComposition: 'Dextromethorphan',
      price: 120,
      originalPrice: 140,
      image: PLACEHOLDER_IMAGES.medicines[2],
      prescriptionRequired: false,
      description: 'Relief from dry cough and throat irritation.',
      benefits: ['Soothes Throat', 'Suppress Cough'],
      sideEffects: ['Drowsiness'],
      directions: '10ml twice a day.',
   },
   {
      id: 'm4',
      name: 'Amoxycillin 500mg',
      manufacturer: 'Antibio',
      saltComposition: 'Amoxycillin',
      price: 85,
      originalPrice: 100,
      image: PLACEHOLDER_IMAGES.medicines[3],
      prescriptionRequired: true,
      description: 'Antibiotic used to treat bacterial infections.',
      benefits: ['Treats Bacterial Infections'],
      sideEffects: ['Diarrhea', 'Nausea'],
      directions: 'As prescribed by the doctor.',
   },
];

export const LAB_TESTS: DiagnosticTest[] = [
   {
      id: 't1',
      name: 'Complete Blood Count (CBC)',
      labName: 'Thyrocare',
      price: 299,
      reportTime: '12 hours',
      description: 'A blood test used to evaluate your overall health and detect a wide range of disorders.',
      image: PLACEHOLDER_IMAGES.tests[0],
      featured: true,
   },
   {
      id: 't2',
      name: 'Thyroid Profile (Total)',
      labName: 'Dr. Lal PathLabs',
      price: 499,
      reportTime: '24 hours',
      description: 'Tests T3, T4, and TSH levels to check thyroid function.',
      image: PLACEHOLDER_IMAGES.tests[1],
      featured: true,
   },
   {
      id: 't3',
      name: 'HbA1c (Glycosylated Hemoglobin)',
      labName: 'Metropolis',
      price: 350,
      reportTime: '8 hours',
      description: 'Measures average blood sugar levels over the past 3 months.',
      image: PLACEHOLDER_IMAGES.tests[2],
      featured: false,
   },
];

export const BANNERS: Offer[] = [
   {
      id: 'b1',
      title: 'Full Body Checkup',
      description: 'Get extensive health insights',
      discount: '50% OFF',
      image: PLACEHOLDER_IMAGES.banners[0],
      code: 'HEALTH50',
      bgColor: 'bg-teal-500',
   },
   {
      id: 'b2',
      title: 'Medicine Delivery',
      description: 'Fastest delivery in town',
      discount: '25% OFF',
      image: PLACEHOLDER_IMAGES.banners[1],
      code: 'MED25',
      bgColor: 'bg-blue-500',
   },
   {
      id: 'b3',
      title: 'Home Physiotherapy',
      description: 'Expert care at home',
      discount: 'Book Now',
      image: PLACEHOLDER_IMAGES.banners[2],
      code: 'PHYSIO',
      bgColor: 'bg-amber-500',
   },
];

export const PHARMACIES: Pharmacy[] = [
   { id: 'ph1', name: 'Apollo Pharmacy', address: 'Indiranagar, Bangalore', price: 30, deliveryTime: '30 mins' },
   { id: 'ph2', name: 'MedPlus', address: 'Koramangala, Bangalore', price: 32, deliveryTime: '45 mins' },
   { id: 'ph3', name: 'Wellness Forever', address: 'Whitefield, Bangalore', price: 29, deliveryTime: '60 mins' },
];

export const BOOKINGS: Booking[] = [
   {
      id: 'bk1',
      serviceId: 'd1',
      serviceName: 'Consultation with Dr. Sharma',
      providerName: 'Health Plus Clinic',
      date: '2023-10-25',
      time: '10:00 AM',
      status: 'upcoming',
      type: 'appointment',
      image: PLACEHOLDER_IMAGES.doctors[0],
   },
   {
      id: 'bk2',
      serviceId: 'm1',
      serviceName: 'Medicine Order',
      providerName: 'Apollo Pharmacy',
      date: '2023-10-20',
      time: '02:00 PM',
      status: 'completed',
      type: 'home-care', // Using home-care for delivery for now or just generic
      image: PLACEHOLDER_IMAGES.medicines[0],
   },
];
